"""empty message

Revision ID: 38289c685dbf
Revises: 3af3f71bd6b5
Create Date: 2025-06-30 19:05:12.936429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38289c685dbf'
down_revision = '3af3f71bd6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
