"""empty message

Revision ID: 4545f43ed558
Revises: c348c9ea484b
Create Date: 2025-06-13 19:05:13.278546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4545f43ed558'
down_revision = 'c348c9ea484b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character', sa.String(length=120), nullable=False))
        batch_op.drop_column('carcter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carcter', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('character')

    # ### end Alembic commands ###
