"""empty message

Revision ID: b4eb2e978ec8
Revises: 38289c685dbf
Create Date: 2025-06-30 19:10:00.939404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eb2e978ec8'
down_revision = '38289c685dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.String(length=600), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('history')

    # ### end Alembic commands ###
